# -*- coding: utf-8 -*-
"""carteiras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RszMRNMayIUKk83Jx7DxmQDBwnsAXpD5
"""

import pandas as pd
import smtplib
import numpy as np
from email.message import EmailMessage
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
import re
import os
!pip install xlsxwriter
import xlsxwriter
arquivos = ['base1']


def verifica_formato_data(data) :
    padrao_data = r'\d{2}-\d{2}-\d{4}'
    data_atual = datetime.now()
    if re.match(padrao_data,data) and len(data) < 11:
      dia = datetime.strptime(data,"%d-%m-%Y")
      dif = data_atual - dia
      return dif.days
    else:
      return 9999

def dias_acionamento(data) :
    padrao_data = r'\d{2}/\d{2}/\d{4}'
    data_atual = datetime.now()
    if re.match(padrao_data,data) and len(data) < 11:
      dia = datetime.strptime(data,"%d/%m/%Y")
      dif = data_atual - dia
      return dif.days
    else:
      return 9999


def database(base,credor):
  if credor == "COMGÁS - PF":
    base.loc[(base['ATRASO']<0),"Faixa de Atraso"] = "INDEFINIDA"
    base.loc[(base['ATRASO']>=0) & (base['ATRASO']<=30),"Faixa de Atraso"] = 'FASE 1 | 0 a 30 | 1%'
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=44),"Faixa de Atraso"] = 'FASE 2 | 31 a 44 | 1%'
    base.loc[(base['ATRASO']>=45) & (base['ATRASO']<=60),"Faixa de Atraso"] = 'FASE 2 | 45 a 60 | 1%'
    base.loc[(base['ATRASO']>=61) & (base['ATRASO']<=90),"Faixa de Atraso"] = 'FASE 3 | 61 a 90 | 3%'
    base.loc[(base['ATRASO']>=91) & (base['ATRASO']<=120),"Faixa de Atraso"] = 'FASE 4 | 91 a 120 | 4%'
    base.loc[(base['ATRASO']>=121) & (base['ATRASO']<=180),"Faixa de Atraso"] = 'FASE 5 | 121 a 180 | 4%'
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=360),"Faixa de Atraso"] ='FASE 6 | 181 a 360 | 6%'
    base.loc[(base['ATRASO']>=361) & (base['ATRASO']<=720),"Faixa de Atraso"] = 'FASE 7 | 361 a 720 | 7%'
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1080),"Faixa de Atraso"] = 'FASE 8 | 721 a 1080 | 8%'
    base.loc[(base['ATRASO']>=1081) & (base['ATRASO']<=1440),"Faixa de Atraso"] = 'FASE 9 | 1081 a 1440 | 9%'
    base.loc[(base['ATRASO']>=1441) & (base['ATRASO']<=99999),"Faixa de Atraso"] = 'FASE 10 | 1441 a 9999 | 10%'

    base.loc[(base['TOTAL ABERTO']<50),"Faixa de preço"] = "De R$ 0 a R$ 49,99"
    base.loc[(base['TOTAL ABERTO']>=50) & (base['TOTAL ABERTO']<100),"Faixa de preço"] = "De R$ 50 a R$ 99,99"
    base.loc[(base['TOTAL ABERTO']>=100) & (base['TOTAL ABERTO']<150),"Faixa de preço"] = "De R$ 100 a R$ 149,99"
    base.loc[(base['TOTAL ABERTO']>=150) & (base['TOTAL ABERTO']<300),"Faixa de preço"] = "De R$ 150 a R$ 299,99"
    base.loc[(base['TOTAL ABERTO']>=300) & (base['TOTAL ABERTO']<500),"Faixa de preço"] = "De R$ 300 a R$ 499,99"
    base.loc[(base['TOTAL ABERTO']>=500) & (base['TOTAL ABERTO']<1000),"Faixa de preço"] = "De R$ 500 a R$ 999,99"
    base.loc[(base['TOTAL ABERTO']>=1000) & (base['TOTAL ABERTO']<5000),"Faixa de preço"] = "De R$ 1000 a R$ 4999,99"
    base.loc[(base['TOTAL ABERTO']>=5000) & (base['TOTAL ABERTO']<999999),"Faixa de preço"] = "De R$ 5000 a R$ 999.999,99"

    base.loc[(base['ATRASO']<0),"% comissão"] = 0
    base.loc[(base['ATRASO']>=0) & (base['ATRASO']<=30),"% comissão"] = 0.01
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=44),"% comissão"] = 0.01
    base.loc[(base['ATRASO']>=45) & (base['ATRASO']<=60),"% comissão"] = 0.01
    base.loc[(base['ATRASO']>=61) & (base['ATRASO']<=90),"% comissão"] = 0.03
    base.loc[(base['ATRASO']>=91) & (base['ATRASO']<=120),"% comissão"] = 0.04
    base.loc[(base['ATRASO']>=121) & (base['ATRASO']<=180),"% comissão"] = 0.04
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=360),"% comissão"] =0.06
    base.loc[(base['ATRASO']>=361) & (base['ATRASO']<=720),"% comissão"] = 0.07
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1080),"% comissão"] = 0.08
    base.loc[(base['ATRASO']>=1081) & (base['ATRASO']<=1440),"% comissão"] = 0.09
    base.loc[(base['ATRASO']>=1441) & (base['ATRASO']<=99999),"% comissão"] = 0.1

  if credor == "TV LAR - COBRANSAAS - PRODUCAO":
    base.loc[(base['ATRASO']<10),"Faixa de Atraso"] = "INDEFINIDA"
    base.loc[(base['ATRASO']>=10) & (base['ATRASO']<=30),"Faixa de Atraso"] = 'FASE 1 | 10 a 30 | 1,5%'
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=60),"Faixa de Atraso"] = 'FASE 2 | 31 a 60 | 2,5%'
    base.loc[(base['ATRASO']>=61) & (base['ATRASO']<=90),"Faixa de Atraso"] = 'FASE 3 | 61 a 90 | 5%'
    base.loc[(base['ATRASO']>=91) & (base['ATRASO']<=120),"Faixa de Atraso"] = 'FASE 4 | 91 a 120 | 7%'
    base.loc[(base['ATRASO']>=121) & (base['ATRASO']<=180),"Faixa de Atraso"] = 'FASE 5 | 121 a 180 | 10%'
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"Faixa de Atraso"] ='FASE 6 | 181 a 240 | 12,5%'
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=360),"Faixa de Atraso"] = 'FASE 7 | 241 a 360 | 14%'
    base.loc[(base['ATRASO']>=361) & (base['ATRASO']<=720),"Faixa de Atraso"] = 'FASE 8 | 361 a 720 | 15%'
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"Faixa de Atraso"] = 'FASE 9 | 721 a 1400 | 25%'
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=99999),"Faixa de Atraso"] = 'FASE 10 | 1401 a 9999 | 30%'

    base.loc[(base['TOTAL ABERTO']<100),"Faixa de preço"] = "A - De R$ 0 a R$ 99,99"
    base.loc[(base['TOTAL ABERTO']>=100) & (base['TOTAL ABERTO']<200),"Faixa de preço"] = "B - De R$ 100 a R$ 199,99"
    base.loc[(base['TOTAL ABERTO']>=200) & (base['TOTAL ABERTO']<500),"Faixa de preço"] = "C - De R$ 200 a R$ 499,99"
    base.loc[(base['TOTAL ABERTO']>=500) & (base['TOTAL ABERTO']<1000),"Faixa de preço"] = "D - De R$ 500 a R$ 999,99"
    base.loc[(base['TOTAL ABERTO']>=1000) & (base['TOTAL ABERTO']<5000),"Faixa de preço"] = "E - De R$ 1000 a R$ 4.999,99"
    base.loc[(base['TOTAL ABERTO']>=5000) & (base['TOTAL ABERTO']<10000),"Faixa de preço"] = "F - De R$ 5000 a R$ 9.999,99"
    base.loc[(base['TOTAL ABERTO']>=10000) & (base['TOTAL ABERTO']<999999),"Faixa de preço"] = "G - De R$ 10000 a R$ 999.999,99"

    base.loc[(base['ATRASO']<10),"% comissão"] = 0
    base.loc[(base['ATRASO']>=10) & (base['ATRASO']<=30),"% comissão"] = 0.015
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=60),"% comissão"] = 0.025
    base.loc[(base['ATRASO']>=61) & (base['ATRASO']<=90),"% comissão"] = 0.05
    base.loc[(base['ATRASO']>=91) & (base['ATRASO']<=120),"% comissão"] = 0.07
    base.loc[(base['ATRASO']>=121) & (base['ATRASO']<=180),"% comissão"] = 0.1
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"% comissão"] = 0.125
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=360),"% comissão"] = 0.14
    base.loc[(base['ATRASO']>=361) & (base['ATRASO']<=720),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"% comissão"] = 0.25
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=99999),"% comissão"] = 0.3

  if credor == "CPET":
    base.loc[(base['ATRASO']<0),"Faixa de Atraso"] = "INDEFINIDA"
    base.loc[(base['ATRASO']>=0) & (base['ATRASO']<=30),"Faixa de Atraso"] = 'FASE 1 | 0 a 30'
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=60),"Faixa de Atraso"] = 'FASE 2 | 31 a 60'
    base.loc[(base['ATRASO']>=61) & (base['ATRASO']<=90),"Faixa de Atraso"] = 'FASE 3 | 61 a 90'
    base.loc[(base['ATRASO']>=91) & (base['ATRASO']<=120),"Faixa de Atraso"] = 'FASE 4 | 91 a 120'
    base.loc[(base['ATRASO']>=121) & (base['ATRASO']<=180),"Faixa de Atraso"] = 'FASE 5 | 121 a 180'
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"Faixa de Atraso"] ='FASE 6 | 181 a 240'
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=360),"Faixa de Atraso"] = 'FASE 7 | 241 a 360'
    base.loc[(base['ATRASO']>=361) & (base['ATRASO']<=720),"Faixa de Atraso"] = 'FASE 8 | 361 a 720'
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"Faixa de Atraso"] = 'FASE 9 | 721 a 1400'
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=99999),"Faixa de Atraso"] = 'FASE 10 | 1401 a 9999'

    base.loc[(base['TOTAL ABERTO']<100),"Faixa de preço"] = "A - De R$ 0 a R$ 99,99"
    base.loc[(base['TOTAL ABERTO']>=100) & (base['TOTAL ABERTO']<200),"Faixa de preço"] = "B - De R$ 100 a R$ 199,99"
    base.loc[(base['TOTAL ABERTO']>=200) & (base['TOTAL ABERTO']<500),"Faixa de preço"] = "C - De R$ 200 a R$ 499,99"
    base.loc[(base['TOTAL ABERTO']>=500) & (base['TOTAL ABERTO']<1000),"Faixa de preço"] = "D - De R$ 500 a R$ 999,99"
    base.loc[(base['TOTAL ABERTO']>=1000) & (base['TOTAL ABERTO']<5000),"Faixa de preço"] = "E - De R$ 1000 a R$ 4.999,99"
    base.loc[(base['TOTAL ABERTO']>=5000) & (base['TOTAL ABERTO']<10000),"Faixa de preço"] = "F - De R$ 5000 a R$ 9.999,99"
    base.loc[(base['TOTAL ABERTO']>=10000) & (base['TOTAL ABERTO']<999999),"Faixa de preço"] = "G - De R$ 10000 a R$ 999.999,99"

    base.loc[(base['ATRASO']<0),"% comissão"] = 0
    base.loc[(base['ATRASO']>=0) & (base['ATRASO']<=30),"% comissão"] = 0
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=60),"% comissão"] = 0
    base.loc[(base['ATRASO']>=61) & (base['ATRASO']<=90),"% comissão"] = 0
    base.loc[(base['ATRASO']>=91) & (base['ATRASO']<=120),"% comissão"] = 0
    base.loc[(base['ATRASO']>=121) & (base['ATRASO']<=180),"% comissão"] = 0
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"% comissão"] = 0
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=360),"% comissão"] = 0
    base.loc[(base['ATRASO']>=361) & (base['ATRASO']<=720),"% comissão"] = 0
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"% comissão"] = 0
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=99999),"% comissão"] = 0

  if credor == "REHAGRO":
    base.loc[(base['ATRASO']<=0),"Faixa de Atraso"] = "INDEFINIDA"
    base.loc[(base['ATRASO']>=1) & (base['ATRASO']<=30),"Faixa de Atraso"] = 'A- 01 a 30'
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=70),"Faixa de Atraso"] = 'B- 31 A 70'
    base.loc[(base['ATRASO']>=71) & (base['ATRASO']<=100),"Faixa de Atraso"] = 'C- 71 a 100'
    base.loc[(base['ATRASO']>=101) & (base['ATRASO']<=140),"Faixa de Atraso"] = 'D-101 A 140'
    base.loc[(base['ATRASO']>=141) & (base['ATRASO']<=180),"Faixa de Atraso"] = 'E- 141 A 180'
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"Faixa de Atraso"] = 'F- 181 A 240'
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=720),"Faixa de Atraso"] = 'G- 241 A 720'
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"Faixa de Atraso"] = 'H- 721 A 1400'
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=1800),"Faixa de Atraso"] = 'I- 1401 A 1800'
    base.loc[(base['ATRASO']>=1801) & (base['ATRASO']<=9999),"Faixa de Atraso"] = 'J- 1801 A 9999'

    base.loc[(base['TOTAL ABERTO']<100),"Faixa de preço"] = "A - De R$ 0 a R$ 99,99"
    base.loc[(base['TOTAL ABERTO']>=100) & (base['TOTAL ABERTO']<200),"Faixa de preço"] = "B - De R$ 100 a R$ 199,99"
    base.loc[(base['TOTAL ABERTO']>=200) & (base['TOTAL ABERTO']<500),"Faixa de preço"] = "C - De R$ 200 a R$ 499,99"
    base.loc[(base['TOTAL ABERTO']>=500) & (base['TOTAL ABERTO']<1000),"Faixa de preço"] = "D - De R$ 500 a R$ 999,99"
    base.loc[(base['TOTAL ABERTO']>=1000) & (base['TOTAL ABERTO']<5000),"Faixa de preço"] = "E - De R$ 1000 a R$ 4.999,99"
    base.loc[(base['TOTAL ABERTO']>=5000) & (base['TOTAL ABERTO']<10000),"Faixa de preço"] = "F - De R$ 5000 a R$ 9.999,99"
    base.loc[(base['TOTAL ABERTO']>=10000) & (base['TOTAL ABERTO']<999999),"Faixa de preço"] = "G - De R$ 10000 a R$ 999.999,99"

    base.loc[(base['ATRASO']<15),"% comissão"] = 0
    base.loc[(base['ATRASO']>=15) & (base['ATRASO']<=30),"% comissão"] = 0
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=90),"% comissão"] = 0.05
    base.loc[(base['ATRASO']>=91) & (base['ATRASO']<=180),"% comissão"] = 0.1
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=600),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=601) & (base['ATRASO']<=1830),"% comissão"] = 0.2
    base.loc[(base['ATRASO']>=1831) & (base['ATRASO']<=99999),"% comissão"] = 0.25

  if credor == "CREDIPAR FINANCEIRA":
    base.loc[(base['ATRASO']<5),"Faixa de Atraso"] = "INDEFINIDA"
    base.loc[(base['ATRASO']>=5) & (base['ATRASO']<=30),"Faixa de Atraso"] = 'A- 05 a 30 | 3%'
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=70),"Faixa de Atraso"] = 'B- 31 A 70 | 9%'
    base.loc[(base['ATRASO']>=71) & (base['ATRASO']<=100),"Faixa de Atraso"] = 'C- 71 a 100 | 15%'
    base.loc[(base['ATRASO']>=101) & (base['ATRASO']<=140),"Faixa de Atraso"] = 'D-101 A 140 | 17%'
    base.loc[(base['ATRASO']>=141) & (base['ATRASO']<=180),"Faixa de Atraso"] = 'E- 141 A 180 | 20%'
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"Faixa de Atraso"] = 'F- 181 A 240 | 24%'
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=720),"Faixa de Atraso"] = 'G- 241 A 720 | 26%'
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"Faixa de Atraso"] = 'H- 721 A 1400 | 30%'
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=1800),"Faixa de Atraso"] = 'I- 1401 A 1800 | 40%'
    base.loc[(base['ATRASO']>=1801) & (base['ATRASO']<=99999),"Faixa de Atraso"] = 'J- 1801 A 9999 | 50%'

    base.loc[(base['TOTAL ABERTO']<100),"Faixa de preço"] = "De R$ 0 a R$ 99,99"
    base.loc[(base['TOTAL ABERTO']>=100) & (base['TOTAL ABERTO']<200),"Faixa de preço"] = "De R$ 100 a R$ 199,99"
    base.loc[(base['TOTAL ABERTO']>=200) & (base['TOTAL ABERTO']<500),"Faixa de preço"] = "De R$ 200 a R$ 499,99"
    base.loc[(base['TOTAL ABERTO']>=500) & (base['TOTAL ABERTO']<1000),"Faixa de preço"] = "De R$ 500 a R$ 999,99"
    base.loc[(base['TOTAL ABERTO']>=1000) & (base['TOTAL ABERTO']<5000),"Faixa de preço"] = "De R$ 1000 a R$ 4.999,99"
    base.loc[(base['TOTAL ABERTO']>=5000) & (base['TOTAL ABERTO']<10000),"Faixa de preço"] = "De R$ 5000 a R$ 9.999,99"
    base.loc[(base['TOTAL ABERTO']>=10000) & (base['TOTAL ABERTO']<999999),"Faixa de preço"] = "De R$ 10000 a R$ 999.999,99"

    base.loc[(base['ATRASO']<5),"% comissão"] = 0
    base.loc[(base['ATRASO']>=5) & (base['ATRASO']<=30),"% comissão"] = 0.03
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=70),"% comissão"] = 0.09
    base.loc[(base['ATRASO']>=71) & (base['ATRASO']<=100),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=101) & (base['ATRASO']<=140),"% comissão"] = 0.17
    base.loc[(base['ATRASO']>=141) & (base['ATRASO']<=180),"% comissão"] = 0.2
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"% comissão"] = 0.24
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=720),"% comissão"] = 0.26
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"% comissão"] = 0.3
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=1800),"% comissão"] = 0.4
    base.loc[(base['ATRASO']>=1801) & (base['ATRASO']<=99999),"% comissão"] = 0.5

  if credor == "A EDUCAÇÃO":
    base.loc[(base['ATRASO']<0),"Faixa de Atraso"] = "INDEFINIDA"
    base.loc[(base['ATRASO']>=1) & (base['ATRASO']<=30),"Faixa de Atraso"] = 'A- 01 a 30 | 10%'
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=70),"Faixa de Atraso"] = 'B- 31 A 70 | 10%'
    base.loc[(base['ATRASO']>=71) & (base['ATRASO']<=100),"Faixa de Atraso"] = 'C- 71 a 100 | 10%'
    base.loc[(base['ATRASO']>=101) & (base['ATRASO']<=140),"Faixa de Atraso"] = 'D-101 A 140 | 10%'
    base.loc[(base['ATRASO']>=141) & (base['ATRASO']<=180),"Faixa de Atraso"] = 'E- 141 A 180 | 10%'
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"Faixa de Atraso"] = 'F- 181 A 240 | 20%'
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=720),"Faixa de Atraso"] = 'G- 241 A 720 | 20%'
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"Faixa de Atraso"] = 'H- 721 A 1400 | 20%'
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=1800),"Faixa de Atraso"] = 'I- 1401 A 1800 | 20%'
    base.loc[(base['ATRASO']>=1801) & (base['ATRASO']<=99999),"Faixa de Atraso"] = 'J- 1801 A 9999 | 20%'

    base.loc[(base['TOTAL ABERTO']<100),"Faixa de preço"] = "A - De R$ 0 a R$ 99,99"
    base.loc[(base['TOTAL ABERTO']>=100) & (base['TOTAL ABERTO']<200),"Faixa de preço"] = "B - De R$ 100 a R$ 199,99"
    base.loc[(base['TOTAL ABERTO']>=200) & (base['TOTAL ABERTO']<500),"Faixa de preço"] = "C - De R$ 200 a R$ 499,99"
    base.loc[(base['TOTAL ABERTO']>=500) & (base['TOTAL ABERTO']<1000),"Faixa de preço"] = "D - De R$ 500 a R$ 999,99"
    base.loc[(base['TOTAL ABERTO']>=1000) & (base['TOTAL ABERTO']<5000),"Faixa de preço"] = "E - De R$ 1000 a R$ 4.999,99"
    base.loc[(base['TOTAL ABERTO']>=5000) & (base['TOTAL ABERTO']<10000),"Faixa de preço"] = "F - De R$ 5000 a R$ 9.999,99"
    base.loc[(base['TOTAL ABERTO']>=10000) & (base['TOTAL ABERTO']<999999),"Faixa de preço"] = "G - De R$ 10000 a R$ 999.999,99"

    base.loc[(base['ATRASO']<0),"% comissão"] = 0
    base.loc[(base['ATRASO']>=1) & (base['ATRASO']<=30),"% comissão"] = 0.1
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=70),"% comissão"] = 0.1
    base.loc[(base['ATRASO']>=71) & (base['ATRASO']<=100),"% comissão"] = 0.1
    base.loc[(base['ATRASO']>=101) & (base['ATRASO']<=140),"% comissão"] = 0.1
    base.loc[(base['ATRASO']>=141) & (base['ATRASO']<=180),"% comissão"] = 0.1
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"% comissão"] = 0.2
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=720),"% comissão"] = 0.2
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"% comissão"] = 0.2
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=1800),"% comissão"] = 0.2
    base.loc[(base['ATRASO']>=1801) & (base['ATRASO']<=99999),"% comissão"] = 0.2
  if credor == "VOTORANTIM":
    base.loc[(base['ATRASO']<5),"Faixa de Atraso"] = "INDEFINIDA"
    base.loc[(base['ATRASO']>=5) & (base['ATRASO']<=30),"Faixa de Atraso"] = 'A- 05 a 30 | 15%'
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=70),"Faixa de Atraso"] = 'B- 31 A 70 | 15%'
    base.loc[(base['ATRASO']>=71) & (base['ATRASO']<=100),"Faixa de Atraso"] = 'C- 71 a 100 | 15%'
    base.loc[(base['ATRASO']>=101) & (base['ATRASO']<=140),"Faixa de Atraso"] = 'D-101 A 140 | 15%'
    base.loc[(base['ATRASO']>=141) & (base['ATRASO']<=180),"Faixa de Atraso"] = 'E- 141 A 180 | 15%'
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"Faixa de Atraso"] = 'F- 181 A 240 | 15%'
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=720),"Faixa de Atraso"] = 'G- 241 A 720 | 15%'
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"Faixa de Atraso"] = 'H- 721 A 1400 | 15%'
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=1800),"Faixa de Atraso"] = 'I- 1401 A 1800 | 15%'
    base.loc[(base['ATRASO']>=1801) & (base['ATRASO']<=99999),"Faixa de Atraso"] = 'J- 1801 A 9999 | 15%'

    base.loc[(base['TOTAL ABERTO']<100),"Faixa de preço"] = "A - De R$ 0 a R$ 99,99"
    base.loc[(base['TOTAL ABERTO']>=100) & (base['TOTAL ABERTO']<200),"Faixa de preço"] = "B - De R$ 100 a R$ 199,99"
    base.loc[(base['TOTAL ABERTO']>=200) & (base['TOTAL ABERTO']<500),"Faixa de preço"] = "C - De R$ 200 a R$ 499,99"
    base.loc[(base['TOTAL ABERTO']>=500) & (base['TOTAL ABERTO']<1000),"Faixa de preço"] = "D - De R$ 500 a R$ 999,99"
    base.loc[(base['TOTAL ABERTO']>=1000) & (base['TOTAL ABERTO']<5000),"Faixa de preço"] = "E - De R$ 1000 a R$ 4.999,99"
    base.loc[(base['TOTAL ABERTO']>=5000) & (base['TOTAL ABERTO']<10000),"Faixa de preço"] = "F - De R$ 5000 a R$ 9.999,99"
    base.loc[(base['TOTAL ABERTO']>=10000) & (base['TOTAL ABERTO']<999999),"Faixa de preço"] = "G - De R$ 10000 a R$ 999.999,99"

    base.loc[(base['ATRASO']<5),"% comissão"] = 0
    base.loc[(base['ATRASO']>=5) & (base['ATRASO']<=30),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=31) & (base['ATRASO']<=70),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=71) & (base['ATRASO']<=100),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=101) & (base['ATRASO']<=140),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=141) & (base['ATRASO']<=180),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=240),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=241) & (base['ATRASO']<=720),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=721) & (base['ATRASO']<=1400),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=1401) & (base['ATRASO']<=1800),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=1801) & (base['ATRASO']<=99999),"% comissão"] = 0.15

  if credor == "SEG":
    base.loc[(base['ATRASO']<30),"Faixa de Atraso"] = "INDEFINIDA"
    base.loc[(base['ATRASO']>=30) & (base['ATRASO']<=90),"Faixa de Atraso"] = 'A- 30 a 90 | 10%'
    base.loc[(base['ATRASO']>=91) & (base['ATRASO']<=180),"Faixa de Atraso"] = 'B- 91 A 180 | 15%'
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=1830),"Faixa de Atraso"] = 'C- 181 a 1830 25%'
    base.loc[(base['ATRASO']>=1831) & (base['ATRASO']<=9999),"Faixa de Atraso"] = 'D- 1831 A 9999 | 40%'

    base.loc[(base['TOTAL ABERTO']<100),"Faixa de preço"] = "A - De R$ 0 a R$ 99,99"
    base.loc[(base['TOTAL ABERTO']>=100) & (base['TOTAL ABERTO']<200),"Faixa de preço"] = "B - De R$ 100 a R$ 199,99"
    base.loc[(base['TOTAL ABERTO']>=200) & (base['TOTAL ABERTO']<500),"Faixa de preço"] = "C - De R$ 200 a R$ 499,99"
    base.loc[(base['TOTAL ABERTO']>=500) & (base['TOTAL ABERTO']<1000),"Faixa de preço"] = "D - De R$ 500 a R$ 999,99"
    base.loc[(base['TOTAL ABERTO']>=1000) & (base['TOTAL ABERTO']<5000),"Faixa de preço"] = "E - De R$ 1000 a R$ 4.999,99"
    base.loc[(base['TOTAL ABERTO']>=5000) & (base['TOTAL ABERTO']<10000),"Faixa de preço"] = "F - De R$ 5000 a R$ 9.999,99"
    base.loc[(base['TOTAL ABERTO']>=10000) & (base['TOTAL ABERTO']<999999),"Faixa de preço"] = "G - De R$ 10000 a R$ 999.999,99"

    base.loc[(base['ATRASO']<30),"% comissão"] = 0
    base.loc[(base['ATRASO']>=30) & (base['ATRASO']<=90),"% comissão"] = 0.1
    base.loc[(base['ATRASO']>=91) & (base['ATRASO']<=180),"% comissão"] = 0.15
    base.loc[(base['ATRASO']>=181) & (base['ATRASO']<=1830),"% comissão"] = 0.25
    base.loc[(base['ATRASO']>=1831) & (base['ATRASO']<=9999),"% comissão"] = 0.4
  return base

tipos = {'Eventos' : ['Importacao',
                      'Acordo Reativado',
                      'Pagamento',
                      'Quebra de Acordo',
                      'Devolução',
                      'Acordo Aprovado',
                      'Acordo',
                      'Exportação Mailing',
                      'Envio de Boleto',
                      'Contato Com Cliente',
                      'Cliente Desconhecido',
                      'Reprovação de Acordo',
                      'Proposta em Análise ',
                      'Recado Com Terceiros',
                      'Ação Whats',
                      'Desligou',
                      'Agendamento',
                      'Confirmação de Pagamento',
                      'Contato Receptivo',
                      'Sem Previsão de Pagamento',
                      'Cliente Não Ouve',
                      'Discagem sem sucesso',
                      'Retorno Discador',
                      'Falecido',
                      'Tentativa de contato via ligação',
                      'Cliente Não Atende','CONTATO TELEFONICO','Envio de Email','Envio de Sms'],
         "TIPO":['NÃO','NÃO','NÃO','NÃO','NÃO','NÃO','SIM','NÃO','SIM','SIM','SIM','NÃO','SIM','SIM','SIM','SIM','SIM','SIM','SIM','SIM','SIM','NÃO','NÃO','SIM','SIM','SIM','SIM','SIM','SIM'],
         "CPC":['NÃO','NÃO','NÃO','NÃO','NÃO','NÃO','SIM','NÃO','SIM','SIM','NÃO','NÃO','SIM','NÃO','NÃO','NÃO','SIM','SIM','SIM','SIM','SIM','NÃO','NÃO','NÃO','NÃO','NÃO','SIM','NÃO','NÃO']}

e = pd.DataFrame(tipos)

e

#for arq in arquivos:
d_type1 = {'CPF/CNPJ':str, 'CONTRATO':str,'CÓD. CLIENTE':str}
d_type2 = {'CPF/CNPJ':str,'NUMERO':str}
d_type3 = {'CPF/CNPJ':str}
d_type4 = {'CPF/CNPJ':str}
d_type5 = {'CPF/CNPJ':str, 'CONTRATO':str,'DATA':str}
cont = pd.read_excel('/content/base1.xlsx',sheet_name='Contratos',dtype= d_type1)
tel = pd.read_excel('/content/base1.xlsx',sheet_name='Telefones',dtype= d_type2)
email = pd.read_excel('/content/base1.xlsx',sheet_name='Emails',dtype= d_type3)
base = pd.read_excel('/content/base1.xlsx',sheet_name='Endereços',dtype= d_type4)
even = pd.read_excel('/content/Cobmais-Eventos.xlsx',sheet_name='Eventos',dtype= d_type5)

even.EVENTO.unique()

cont.columns

credor = cont['CREDOR'][0]
print(credor)

cont = cont[['CPF/CNPJ', 'CLIENTE', 'CREDOR', 'CONTRATO','INCLUSAO','ESTAGIO', 'PRODUTO','FILIAL','ATRASO', 'DEFASAGEM', 'PARCELAS','TOTAL ABERTO', 'TOTAL PARCELAS']]
cont1 = cont.drop_duplicates(subset='CONTRATO')

df1 = database(cont1,credor)
df1['RECEITA'] = df1['TOTAL ABERTO']*df1['% comissão']
df1 = df1[['CPF/CNPJ','CLIENTE', 'CREDOR', 'CONTRATO', 'INCLUSAO','ATRASO','ESTAGIO','DEFASAGEM','TOTAL ABERTO', 'Faixa de Atraso', '% comissão', 'RECEITA','Faixa de preço']]
df1 = df1.rename(columns={'CPF/CNPJ':'CPF_CNPJ'})

end = base[['CPF/CNPJ','UF']]
end = end.rename(columns={'CPF/CNPJ':'CPF_CNPJ'})
end.fillna(value="",inplace=True)
end1 = end.loc[end['UF']!=""]
end1 = end1.drop_duplicates(subset='CPF_CNPJ')

df2 = pd.merge(df1,end1,how="left",on="CPF_CNPJ")

vlr_b1 = df2.groupby(['Faixa de Atraso']).count()
vlr_b2 = df2.groupby(['Faixa de Atraso']).sum(numeric_only=True)
vlr_b3 = df2.groupby(['Faixa de preço']).count()
vlr_b4 = df2.groupby(['Faixa de preço']).sum(numeric_only=True)
vlr_b5 = df2.groupby(['UF']).count()
vlr_b6 = df2.groupby(['UF']).sum(numeric_only=True)
vlr_b1 = vlr_b1[['RECEITA']]
vlr_b2 = vlr_b2[['TOTAL ABERTO','RECEITA']]
vlr_b3 = vlr_b3[['RECEITA']]
vlr_b4 = vlr_b4[['TOTAL ABERTO','RECEITA']]
vlr_b5 = vlr_b5[['RECEITA']]
vlr_b6 = vlr_b6[['TOTAL ABERTO','RECEITA']]
fx_a = pd.merge(vlr_b1,vlr_b2,left_index=True,right_index=True)
fx_p = pd.merge(vlr_b3,vlr_b4,left_index=True,right_index=True)
fx_r = pd.merge(vlr_b5,vlr_b6,left_index=True,right_index=True)
fx_p = fx_p.rename(columns={'RECEITA_x':'QTDE CONTRATOS','RECEITA_y':'RECEITA' })
fx_a = fx_a.rename(columns={'RECEITA_x':'QTDE CONTRATOS','RECEITA_y':'RECEITA' })
fx_r = fx_r.rename(columns={'RECEITA_x':'QTDE CONTRATOS','RECEITA_y':'RECEITA' })

tel1 = tel[['CPF/CNPJ','NUMERO','CONTATO','WHATSAPP','TIPO','ATIVO','OBSERVAÇÃO']]
tel1['OBSLEMITTI'] = tel1['OBSERVAÇÃO'].str.split("|",n=1,expand=True)[0]
tel1.fillna(value="",inplace= True)
tel1['LEMITTI'] = tel1['OBSLEMITTI'].str.split(" ",n=2,expand=True)[0]
tel1['DIA_HIG'] = tel1['OBSLEMITTI'].str.split(" ",n=2,expand=True)[1]
tel1['HIG'] = np.where(tel1['LEMITTI'].isin(['LEMIT','Lemit']),'SIM','NÃO')
tel1['qtde_dg'] = tel1['NUMERO'].apply(lambda x : len(x))

tel1['Num_valido'] = np.where(tel1['qtde_dg']>9,"VALIDO","INVALIDO")
tel1.fillna(value="",inplace=True)
tel1['DIA_HIG'] = tel1['DIA_HIG'].apply(lambda x : x.replace(" ","").replace("/","-").replace(".","-"))

tel1

tel2 = tel1
tel2['DIAS'] = tel2['DIA_HIG'].apply(lambda x : verifica_formato_data(x))
tel2['Per_valido'] = np.where(tel2['DIAS']>125,"INVALIDO","VALIDO")

tel2 = tel2[['CPF/CNPJ', 'NUMERO', 'CONTATO', 'TIPO','WHATSAPP', 'ATIVO', 'OBSERVAÇÃO', 'LEMITTI', 'DIA_HIG', 'HIG', 'qtde_dg', 'Num_valido','DIAS','Per_valido']]

teles1 = tel2.groupby(['TIPO','ATIVO','HIG','Per_valido']).count()
teles1 = teles1[['CPF/CNPJ']]
teles2 = tel2.groupby(['HIG','ATIVO','Per_valido']).count()
teles2 = teles2[['CPF/CNPJ']]
teles3 = tel2.groupby(['CPF/CNPJ','ATIVO','TIPO','HIG','Per_valido']).count()
teles3 = teles3[['CONTATO']]
cpf_qtde = tel2.groupby(['CPF/CNPJ']).count()
cpf_qtde = cpf_qtde[['CONTATO']]

cpf_mov = tel2.loc[tel2['TIPO']=='MOVEL']
cpf_mov = cpf_mov.groupby(['CPF/CNPJ']).count()
cpf_mov = cpf_mov[['CONTATO']]

cpf_wpp = tel2.loc[(tel2['WHATSAPP']=='SIM')&(tel2['ATIVO']=='SIM')]
cpf_wpp = cpf_wpp.groupby(['CPF/CNPJ']).count()
cpf_wpp = cpf_wpp[['CONTATO']]

cpf_ctt = tel2.loc[(tel2['CONTATO']=='SIM')&(tel2['ATIVO']=='SIM')]
cpf_ctt = cpf_ctt.groupby(['CPF/CNPJ']).count()
cpf_ctt = cpf_ctt[['WHATSAPP']]

cpf_res = tel2.loc[tel2['TIPO']=='RESIDENCIAL']
cpf_res = cpf_res.groupby(['CPF/CNPJ']).count()
cpf_res = cpf_res[['CONTATO']]
cpf_ati =  tel2.loc[tel2['ATIVO']=='SIM']
cpf_ati = cpf_ati.groupby(['CPF/CNPJ']).count()
cpf_ati = cpf_ati[['CONTATO']]
cpf_lemit = tel2.loc[tel2['HIG']=='SIM']
cpf_lemit = cpf_lemit.groupby(['CPF/CNPJ']).count()
cpf_lemit = cpf_lemit[['CONTATO']]
cpf_lem_ati = tel2.loc[tel2['HIG']=='SIM']
cpf_lem_ati = cpf_lem_ati.loc[cpf_lem_ati['ATIVO']=='SIM']
cpf_lem_ati = cpf_lem_ati.groupby(['CPF/CNPJ']).count()
cpf_lem_ati = cpf_lem_ati[['CONTATO']]
cpf_lemt_v = tel2.loc[tel2['HIG']=='SIM']
cpf_lemt_v = cpf_lemt_v.loc[tel2['Per_valido']=='VALIDO']
cpf_lemt_v = cpf_lemt_v.groupby(['CPF/CNPJ']).count()
cpf_lemt_v = cpf_lemt_v[['CONTATO']]
cpf_lemt_v_a = tel2.loc[tel2['HIG']=='SIM']
cpf_lemt_v_a = cpf_lemt_v_a.loc[tel2['Per_valido']=='VALIDO']
cpf_lemt_v_a = cpf_lemt_v_a.loc[tel2['ATIVO']=='SIM']
cpf_lemt_v_a = cpf_lemt_v_a.groupby(['CPF/CNPJ']).count()
cpf_lemt_v_a = cpf_lemt_v_a[['CONTATO']]

num_cpf_tel = pd.merge(cpf_qtde,cpf_mov,left_index=True,right_index=True,how='left')
num_cpf_tel = pd.merge(num_cpf_tel,cpf_res,left_index=True,right_index=True,how='left')
num_cpf_tel.rename(columns={'CONTATO_x': 'Qtde telefone', 'CONTATO_y': 'Qtde tel Moveis','CONTATO': 'Qtde tel Resid.'}, inplace=True)

num_cpf_tel = pd.merge(num_cpf_tel,cpf_ati,left_index=True,right_index=True,how='left')
num_cpf_tel.rename(columns={'CONTATO': 'Qtde Contatos ativos'}, inplace=True)
num_cpf_tel = pd.merge(num_cpf_tel,cpf_lemit,left_index=True,right_index=True,how='left')
num_cpf_tel.rename(columns={'CONTATO': 'Qtde tels Higienizados'}, inplace=True)
num_cpf_tel = pd.merge(num_cpf_tel,cpf_lem_ati,left_index=True,right_index=True,how='left')
num_cpf_tel.rename(columns={'CONTATO': 'Qtde tels Higi ativos'}, inplace=True)
num_cpf_tel = pd.merge(num_cpf_tel,cpf_lemt_v,left_index=True,right_index=True,how='left')
num_cpf_tel.rename(columns={'CONTATO': 'Qtde tels Higi periodo valido'}, inplace=True)
num_cpf_tel = pd.merge(num_cpf_tel,cpf_lemt_v_a,left_index=True,right_index=True,how='left')
num_cpf_tel.rename(columns={'CONTATO': 'Qtde tels Higienizados ativos validos'}, inplace=True)
num_cpf_tel = pd.merge(num_cpf_tel,cpf_wpp,left_index=True,right_index=True,how='left')
num_cpf_tel.rename(columns={'CONTATO': 'Qtde tels WPP'}, inplace=True)
num_cpf_tel = pd.merge(num_cpf_tel,cpf_ctt,left_index=True,right_index=True,how='left')
num_cpf_tel.rename(columns={'WHATSAPP': 'Qtde tels CPC'}, inplace=True)
num_cpf_tel.fillna(value=0,inplace=True)

df = pd.merge(df2,num_cpf_tel,left_on='CPF_CNPJ',right_index=True,how='outer')

bas_e = email.loc[email['ATIVO']=='SIM']
bas_e1 = bas_e.groupby(['CPF/CNPJ']).count()
bas_e1 = bas_e1[['ATIVO']]
bas_e1.rename(columns={'ATIVO':'QTDE EMAILS'},inplace=True)

tels = tel1.loc[tel1['ATIVO']=='SIM']

ev = pd.merge(even,e,left_on='EVENTO',right_on='Eventos',how='left')
ev['CHAVE'] = ev['CPF/CNPJ'] + ev['DATA'] + ev['EVENTO']
evc = ev.drop_duplicates(subset='CHAVE')

ev1  = evc.loc[ev['TIPO']=='SIM']
ev1

ev1['data'] = ev1['DATA'].str.split(" ",n=1,expand=True)[0]
ev1['DIAS'] = ev1['data'].apply(lambda x : dias_acionamento(x))

ev2 = ev1.groupby(['CPF/CNPJ']).count()
ev2 = ev2[['DIAS']]
ev2.rename(columns={'DIAS':'QTDE ACIONAMENTO'},inplace=True)

ev3 = ev1[['CPF/CNPJ','DIAS']]
min3 = ev3.groupby(['CPF/CNPJ']).min()
min3.rename(columns={'DIAS':'DIAS ULT. ACIO.'},inplace=True)

ev4 = ev1.loc[ev1['CPC']=='SIM']
ev4 = ev4[['CPF/CNPJ','DIAS']]
min4 = ev4.groupby(['CPF/CNPJ']).min()
min4.rename(columns={'DIAS':'DIAS ULT. ACIO. POS'},inplace=True)

min5 = ev4.groupby(['CPF/CNPJ']).count()
min5.rename(columns={'DIAS':'QTDE ACIO. POS'},inplace=True)


even1 = pd.merge(ev2,min3,left_index=True,right_index=True,how='outer')
even1 = pd.merge(even1,min4,left_index=True,right_index=True,how='outer')
even1 = pd.merge(even1,min5,left_index=True,right_index=True,how='outer')
even1['DIAS ULT. ACIO. POS'].fillna(value=9999,inplace=True)
even1['DIAS ULT. ACIO.'].fillna(value=9999,inplace=True)
even1['QTDE ACIO. POS'].fillna(value=0,inplace=True)
even1['QTDE ACIONAMENTO'].fillna(value=0,inplace=True)

#maior atraso
m_a = cont[['CPF/CNPJ','ATRASO','DEFASAGEM']]
m_a = m_a.groupby(['CPF/CNPJ']).max()

inf = cont.drop_duplicates(subset='CONTRATO')
inf = inf.groupby(['CPF/CNPJ']).sum(numeric_only=True)

inf = inf[['PARCELAS','TOTAL ABERTO', 'TOTAL PARCELAS']]
bas = pd.merge(inf,m_a,left_index=True,right_index=True,how='outer')
bas1 = database(bas,credor)
bas1['RECEITA'] = bas1['TOTAL ABERTO']*bas1['% comissão']
res = pd.merge(bas1,num_cpf_tel,left_index=True,right_index=True,how='outer')
res = pd.merge(end1,res,left_on='CPF_CNPJ',right_index=True,how='outer')
res = pd.merge(res,bas_e1,left_on='CPF_CNPJ',right_index=True,how='outer')
res = pd.merge(res,even1,left_on='CPF_CNPJ',right_index=True,how='left')
res.fillna(value=0,inplace=True)

with pd.ExcelWriter(f'Base_resumida_por_CPF_{credor}_{datetime.today().strftime("%d-%m-%Y")}.xlsx',engine='xlsxwriter') as writer:
  res.to_excel(writer,index=False,sheet_name='BASE RESUMIDA')
  tels.to_excel(writer,index=False,sheet_name='TELEFONES')
  bas_e.to_excel(writer,index=False,sheet_name='EMAILS')
writer.close()

with pd.ExcelWriter(f'Base de infos _{credor}_({datetime.today().strftime("%d-%m-%Y")}).xlsx',engine='xlsxwriter') as writer:
  df.to_excel(writer,index=False,sheet_name='BASE DETALHADA')
  res.to_excel(writer,index=False,sheet_name='BASE RESUMIDA')
  fx_a.to_excel(writer,index=True,sheet_name='FAIXA DE ATRASO')
  fx_p.to_excel(writer,index=True,sheet_name='FAIXA DE PREÇO')
  fx_r.to_excel(writer,index=True,sheet_name='VALOR DE BASE UF')
  teles1.to_excel(writer,index=True,sheet_name='TIPO DE TEL')
  teles2.to_excel(writer,index=True,sheet_name='NUMEROS HIG QTDE')
  tels.to_excel(writer,index=False,sheet_name='TELEFONES')
  bas_e.to_excel(writer,index=False,sheet_name='EMAILS')
writer.close()

res

evc

even1

len(res)

